version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: kinghost_back
    volumes:
      - ./backend:/var/www/backend
    networks:
      - kinghost_network

  webserver:
    image: nginx:alpine
    container_name: kinghost_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/backend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - kinghost_network

  mysql:
    image: mysql:8.0
    container_name: kinghost_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kinghost_catalog
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: kinghost_user
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - kinghost_network

  frontend:
    image: node:20-alpine
    container_name: kinghost_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - kinghost_network

networks:
  kinghost_network:
    driver: bridge
